// Generated by CoffeeScript 1.6.2
var request, url;

request = require('http');

url = 'http://localhost:1337/';

describe('basic coffee test', function() {
  return it('should pass', function() {
    return expect(1 + 2).toBe(3);
  });
});

describe('web service', function() {
  return it('should respond to /ping', function(done) {
    return request.get(url + 'ping', function(res) {
      expect(res.statusCode).toBe(200);
      return res.on('data', function(body) {
        var json;

        json = JSON.parse(body);
        expect(json.message).toBe("Hi, I'm alive");
        expect(json.date).toBeDefined();
        return done();
      });
    });
  });
});
