// Generated by CoffeeScript 1.6.2
var Model;

Model = require('../db.js').models.IdeaType;

module.exports = {
  list: function(req, res, next) {
    return Model.findAll().success(function(models) {
      return res.send(models);
    });
  },
  count: function(req, res, next) {
    return Model.count().success(function(count) {
      return res.send(count.toString());
    });
  },
  show: function(req, res, next) {
    var id;

    id = parseInt(req.params.id, 10);
    return Model.find(id).success(function(model) {
      return res.send(model);
    });
  }
};
